[package]
name = "formatter"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "formatter"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.27.0"
xmlformat = "1.2.1"
